#!/bin/bash

# -- UTF 8 --

iptables="/sbin/iptables"

# Cadena (Usar INPUT si el firewall se ejecuta en el mismo servidor a proteger y usar FORWARD si el firewall se ejecuta en un host aparte y está conectado al Servidor a proteger)

CADENA="FORWARD"

# Limpiar tablas

$iptables -F

$iptables -X

$iptables -Z

# Definir política por defecto

$iptables -P INPUT ACCEPT

$iptables -P FORWARD ACCEPT

$iptables -P OUTPUT ACCEPT

# Conteo de paquetes por protocolo

$iptables -N Conteo

$iptables -A $CADENA -p icmp -j Conteo

$iptables -A $CADENA -p tcp -j Conteo

$iptables -A $CADENA -p udp -j Conteo

# Cadenas extra de bloqueos

$iptables -N sshbrute

$iptables -N blacklist1

$iptables -N tcpflood

$iptables -N blacklist2

$iptables -N udpflood

$iptables -N blacklist3

# Parámetros del firewall

# IP WEB SERVER

IPWS="10.0.0.2"

# INTERFAZ DE ENTRADA

IFACE_Nro1="eth0"

# INTERFAZ DE SALIDA

IFACE_Nro2="eth1"


# Módulos de iptables


