#!/bin/bash
# -- UTF 8 --


# ICMP

iptables -L FORWARD -v -x -n | grep "Conteo" | grep "icmp" > ./Conteo_aux/icmp_aux

# Elimina los espacios en blanco que se encuentran al principio con el comando sed y despu?s convierte los espacios m?ltiples en un s?lo espacio

sed 's/^ *//g' ./Conteo_aux/icmp_aux | fmt -u > ./Conteo_aux/icmp_aux_2

var1=ICMP:

var2=`cut -f 1 -d ' ' ./Conteo_aux/icmp_aux_2`

var3=`cut -f 2 -d ' ' ./Conteo_aux/icmp_aux_2`

var4=Paquetes

var5=Bytes

var6=`echo $var1 $var2 $var4 $var3 $var5`

# TCP

iptables -L FORWARD -v -x -n | grep "Conteo" | grep "tcp" > ./Conteo_aux/tcp_aux

# Elimina los espacios en blanco que se encuentran al principio con el comando sed y después convierte los espacios múltiples en un sólo espacio

sed 's/^ *//g' ./Conteo_aux/tcp_aux | fmt -u > ./Conteo_aux/tcp_aux_2

var7=TCP:

var8=`cut -f 1 -d ' ' ./Conteo_aux/tcp_aux_2`

var9=`cut -f 2 -d ' ' ./Conteo_aux/tcp_aux_2`

var10=`echo $var7 $var8 $var4 $var9 $var5`

# UDP

iptables -L FORWARD -v -x -n | grep "Conteo" | grep "udp" > ./Conteo_aux/udp_aux

# Elimina los espacios en blanco que se encuentran al principio con el comando sed y despu?s convierte los espacios m?ltiples en un s?lo espacio

sed 's/^ *//g' ./Conteo_aux/udp_aux | fmt -u > ./Conteo_aux/udp_aux_2

var11=UDP:

var12=`cut -f 1 -d ' ' ./Conteo_aux/udp_aux_2`

var13=`cut -f 2 -d ' ' ./Conteo_aux/udp_aux_2`

var14=`echo $var11 $var12 $var4 $var13 $var5`

# Guardar en archivo

echo -e $var6\\n$var10\\n$var14 > ./registro_conteo
