#!/bin/bash
# -- UTF 8 --

# Aceptado

# El comando sed elimina los espacios en blanco que se encuentran al principio, después el comando fmt convierte los espacios múltiples en un sólo espacio. Luego se utiliza el comando cut para mostrar un solo campo.

iptables -L FORWARD -v -x -n | grep "ACCEPT" | fmt -u -w 2000 ./Estado_aux/aceptado_aux | sed 's/^ *//g' > ./Estado_aux/aceptado_aux

var1=Aceptado:

var2=Paquetes

var3=Bytes

varA=`sed -n '1p' ./Estado_aux/aceptado_aux | cut -f 5 -d ' '`

varB=`sed -n '1p' ./Estado_aux/aceptado_aux | cut -f 7 -d ' ' `

echo $varA $varB >> ./Estado_aux/aceptado_aux

suma1=`sed '1d' ./Estado_aux/aceptado_aux | cut -f 1 -d ' ' | paste -sd+ | bc`

suma2=`sed '1d' ./Estado_aux/aceptado_aux | cut -f 2 -d ' ' | paste -sd+ | bc`

var4=`echo $var1 $suma1 $var2 $suma2 $var3`

# Descartado

iptables -L FORWARD -v -x -n | grep "DROP" | fmt -u -w 2000 | sed 's/^ *//g' > ./Estado_aux/descartado_aux

var5=Descartado:

echo 0 0 >> ./Estado_aux/descartado_aux

suma3=`cut -f 1 -d ' ' ./Estado_aux/descartado_aux | paste -sd+ | bc`

suma4=`cut -f 2 -d ' ' ./Estado_aux/descartado_aux | paste -sd+ | bc`

var6=`echo $var5 $suma3 $var2 $suma4 $var3`

# Rechazado

iptables -L FORWARD -v -x -n | grep "REJECT" | fmt -u -w 2000 | sed 's/^ *//g' > ./Estado_aux/rechazado_aux

var7=Rechazado:

echo 0 0 >> ./Estado_aux/rechazado_aux

suma5=`cut -f 1 -d ' ' ./Estado_aux/rechazado_aux | paste -sd+ | bc`

suma6=`cut -f 2 -d ' ' ./Estado_aux/rechazado_aux | paste -sd+ | bc`

var8=`echo $var7 $suma5 $var2 $suma6 $var3`

# Guardar en archivo

echo -e $var4\\n$var6\\n$var8 > ./registro_estado
