#!/bin/bash

# -- UTF 8 --

iptables="/sbin/iptables"

# Cadena (Usar INPUT si el firewall se ejecuta en el mismo servidor a proteger y usar FORWARD si el firewall se ejecuta en un host aparte y está conectado al Servidor a proteger)

CADENA="FORWARD"

# Limpiar tablas

$iptables -F

$iptables -X

$iptables -Z

# Definir política por defecto

$iptables -P INPUT ACCEPT

$iptables -P FORWARD ACCEPT

$iptables -P OUTPUT ACCEPT

# Conteo de paquetes por protocolo

$iptables -N Conteo

$iptables -A $CADENA -p icmp -j Conteo

$iptables -A $CADENA -p tcp -j Conteo

$iptables -A $CADENA -p udp -j Conteo

# Cadenas extra de bloqueos

$iptables -N sshbrute

$iptables -N blacklist1

$iptables -N tcpflood

$iptables -N blacklist2

$iptables -N udpflood

$iptables -N blacklist3

# Parámetros del firewall

# IP WEB SERVER

IPWS="10.0.0.2"

# INTERFAZ DE ENTRADA

IFACE_Nro1="eth0"

# INTERFAZ DE SALIDA

IFACE_Nro2="eth1"


# Módulos de iptables


# IP WEB SERVER

IPWS="10.0.0.1"

# INTERFAZ DE ENTRADA

IFACE_Nro1="eth0"

# INTERFAZ DE SALIDA

IFACE_Nro2="eth1"


# Módulos de iptables


# Módulo Nro 2: ICMP FLOODING

# Bloqueo de mensajes ICMP que generan respuesta. Se evita que el firewall sea detectado mediante la devolución de un mensaje de host inalcanzable. Se descartan todos los paquetes y se envia un mensaje de host inalcanzable cada 1 minuto

# Mensajes de solicitud (que generan respuesta):

# echo-request
# timestamp-request
# information-request (Obsoleto)
# address-mask-request (No responde)
# router-solicitation (No responde)


# Bloqueo de mensaje echo-request


$iptables -A $CADENA -i $IFACE_Nro1 -d $IPWS -p icmp --icmp-type echo-request -j LOG --log-prefix "ICMP echo-request: " --log-level 4

$iptables -A $CADENA -i $IFACE_Nro1 -d $IPWS -p icmp --icmp-type echo-request -m limit --limit 1/minute --limit-burst 1 -j REJECT --reject-with icmp-host-unreachable

$iptables -A $CADENA -i $IFACE_Nro1 -d $IPWS -p icmp --icmp-type echo-request -j DROP


# Bloqueo de mensaje timestamp-request


$iptables -A $CADENA -i $IFACE_Nro1 -d $IPWS -p icmp --icmp-type timestamp-request -j LOG --log-prefix "ICMP timestamp-request: " --log-level 4

$iptables -A $CADENA -i $IFACE_Nro1 -d $IPWS -p icmp --icmp-type timestamp-request -m limit --limit 1/minute --limit-burst 1 -j REJECT --reject-with icmp-host-unreachable

$iptables -A $CADENA -i $IFACE_Nro1 -d $IPWS -p icmp --icmp-type timestamp-request -j DROP



# IP WEB SERVER

IPWS="10.0.0.1"

# INTERFAZ DE ENTRADA

IFACE_Nro1="eth0"

# INTERFAZ DE SALIDA

IFACE_Nro2="eth1"


# Módulos de iptables


# Módulo Nro 2: ICMP FLOODING

# Bloqueo de mensajes ICMP que generan respuesta. Se evita que el firewall sea detectado mediante la devolución de un mensaje de host inalcanzable. Se descartan todos los paquetes y se envia un mensaje de host inalcanzable cada 1 minuto

# Mensajes de solicitud (que generan respuesta):

# echo-request
# timestamp-request
# information-request (Obsoleto)
# address-mask-request (No responde)
# router-solicitation (No responde)


# Bloqueo de mensaje echo-request


$iptables -A $CADENA -i $IFACE_Nro1 -d $IPWS -p icmp --icmp-type echo-request -j LOG --log-prefix "ICMP echo-request: " --log-level 4

$iptables -A $CADENA -i $IFACE_Nro1 -d $IPWS -p icmp --icmp-type echo-request -m limit --limit 1/minute --limit-burst 1 -j REJECT --reject-with icmp-host-unreachable

$iptables -A $CADENA -i $IFACE_Nro1 -d $IPWS -p icmp --icmp-type echo-request -j DROP


# Bloqueo de mensaje timestamp-request


$iptables -A $CADENA -i $IFACE_Nro1 -d $IPWS -p icmp --icmp-type timestamp-request -j LOG --log-prefix "ICMP timestamp-request: " --log-level 4

$iptables -A $CADENA -i $IFACE_Nro1 -d $IPWS -p icmp --icmp-type timestamp-request -m limit --limit 1/minute --limit-burst 1 -j REJECT --reject-with icmp-host-unreachable

$iptables -A $CADENA -i $IFACE_Nro1 -d $IPWS -p icmp --icmp-type timestamp-request -j DROP



# IP WEB SERVER

IPWS="10.0.0.1"

# INTERFAZ DE ENTRADA

IFACE_Nro1="eth0"

# INTERFAZ DE SALIDA

IFACE_Nro2="eth1"


# Módulos de iptables


# Módulo Nro 2: ICMP FLOODING

# Bloqueo de mensajes ICMP que generan respuesta. Se evita que el firewall sea detectado mediante la devolución de un mensaje de host inalcanzable. Se descartan todos los paquetes y se envia un mensaje de host inalcanzable cada 1 minuto

# Mensajes de solicitud (que generan respuesta):

# echo-request
# timestamp-request
# information-request (Obsoleto)
# address-mask-request (No responde)
# router-solicitation (No responde)


# Bloqueo de mensaje echo-request


$iptables -A $CADENA -i $IFACE_Nro1 -d $IPWS -p icmp --icmp-type echo-request -j LOG --log-prefix "ICMP echo-request: " --log-level 4

$iptables -A $CADENA -i $IFACE_Nro1 -d $IPWS -p icmp --icmp-type echo-request -m limit --limit 1/minute --limit-burst 1 -j REJECT --reject-with icmp-host-unreachable

$iptables -A $CADENA -i $IFACE_Nro1 -d $IPWS -p icmp --icmp-type echo-request -j DROP


# Bloqueo de mensaje timestamp-request


$iptables -A $CADENA -i $IFACE_Nro1 -d $IPWS -p icmp --icmp-type timestamp-request -j LOG --log-prefix "ICMP timestamp-request: " --log-level 4

$iptables -A $CADENA -i $IFACE_Nro1 -d $IPWS -p icmp --icmp-type timestamp-request -m limit --limit 1/minute --limit-burst 1 -j REJECT --reject-with icmp-host-unreachable

$iptables -A $CADENA -i $IFACE_Nro1 -d $IPWS -p icmp --icmp-type timestamp-request -j DROP



