#!/bin/bash
# -- UTF 8 --

# Aceptado

# El comando sed elimina los espacios en blanco que se encuentran al principio, después el comando fmt convierte los espacios múltiples en un sólo espacio. Luego se utiliza el comando cut para mostrar un solo campo.

var1=Aceptado:

var2=Paquetes

var3=Bytes

varA=`iptables -L FORWARD -v -x -n | grep "ACCEPT" | awk '/Chain/ { print $5 }'`

varB=`iptables -L FORWARD -v -x -n | grep "ACCEPT" | awk '/Chain/ { print $7 }'`

suma1=`iptables -L FORWARD -v -x -n | grep "ACCEPT" | awk '{ sum += $1 } END { print sum+0+variableA }' variableA=$varA`

suma2=`iptables -L FORWARD -v -x -n | grep "ACCEPT" | awk '{ sum += $2 } END { print sum+0+variableB }' variableB=$varB`

var4=`echo $var1 $suma1 $var2 $suma2 $var3`

# Descartado

var5=Descartado:

varC=`iptables -L FORWARD -v -x -n | grep "DROP" | awk '/Chain/ { print $5 }'`

varD=`iptables -L FORWARD -v -x -n | grep "DROP" | awk '/Chain/ { print $7 }'`

cadA1=`iptables -L blacklist1 -v -x -n | grep "DROP" | awk '{ print $1 }'`
cadA2=`iptables -L blacklist1 -v -x -n | grep "DROP" | awk '{ print $2 }'`
cadB1=`iptables -L blacklist2 -v -x -n | grep "DROP" | awk '{ print $1 }'`
cadB2=`iptables -L blacklist2 -v -x -n | grep "DROP" | awk '{ print $2 }'`
cadC1=`iptables -L blacklist3 -v -x -n | grep "DROP" | awk '{ print $1 }'`
cadC2=`iptables -L blacklist3 -v -x -n | grep "DROP" | awk '{ print $2 }'`
cadD1=`iptables -L sshbrute -v -x -n | grep "DROP" | awk '{ print $1 }'`
cadD2=`iptables -L sshbrute -v -x -n | grep "DROP" | awk '{ print $2 }'`
cadE1=`iptables -L tcpflood -v -x -n | grep "DROP" | awk '{ print $1 }'`
cadE2=`iptables -L tcpflood -v -x -n | grep "DROP" | awk '{ print $2 }'`
cadF1=`iptables -L udpflood -v -x -n | grep "DROP" | awk '{ print $1 }'`
cadF2=`iptables -L udpflood -v -x -n | grep "DROP" | awk '{ print $2 }'`

suma3=`iptables -L FORWARD -v -x -n | grep "DROP" | awk '{ sum += $1 } END { print sum+0+variableC+cadenaA1+cadenaB1+cadenaC1+cadenaD1+cadenaE1+cadenaF1 }' variableC=$varC cadenaA1=$cadA1 cadenaB1=$cadB1 cadenaC1=$cadC1 cadenaD1=$cadD1 cadenaE1=$cadE1 cadenaF1=$cadF1`

suma4=`iptables -L FORWARD -v -x -n | grep "DROP" | awk '{ sum += $2 } END { print sum+0+variableD+cadenaA2+cadenaB2+cadenaC2+cadenaD2+cadenaE2+cadenaF2 }' variableD=$varD cadenaA2=$cadA2 cadenaB2=$cadB2 cadenaC2=$cadC2 cadenaD2=$cadD2 cadenaE2=$cadE2 cadenaF2=$cadF2`

var6=`echo $var5 $suma3 $var2 $suma4 $var3`

# Rechazado

var7=Rechazado:

suma5=`iptables -L FORWARD -v -x -n | grep "REJECT" | awk '{ sum += $1 } END { print sum+0 }'`

suma6=`iptables -L FORWARD -v -x -n | grep "REJECT" | awk '{ sum += $2 } END { print sum+0 }'`

var8=`echo $var7 $suma5 $var2 $suma6 $var3`

# Guardar en archivo

echo -e $var4\\n$var6\\n$var8 > ../src/registro_estado
