#!/bin/bash

# -- UTF 8 --

iptables="/sbin/iptables"

# Cadena (Usar INPUT si el firewall se ejecuta en el mismo servidor a proteger y usar FORWARD si el firewall se ejecuta en un host aparte y est? conectado al Servidor a proteger)

CADENA="FORWARD"

# Regla cargada manualmente

