#!/bin/bash
# -- UTF 8 --

var1="#!/bin/bash"

var2="# -- UTF 8 --"

var3="iptables=\"/sbin/iptables\""

var4="# Cadena (Usar INPUT si el firewall se ejecuta en el mismo servidor a proteger y usar FORWARD si el firewall se ejecuta en un host aparte y est? conectado al Servidor a proteger)"

var5="CADENA=\"FORWARD\""

var6="# Regla cargada manualmente"


# Guardar en archivo

echo -e $var1\\n\\n$var2\\n\\n$var3\\n\\n$var4\\n\\n$var5\\n\\n$var6\\n > ./regla
